<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>5164023.ico</ApplicationIcon>
	<PublishSingleFile>true</PublishSingleFile>
	  <SelfContained>true</SelfContained>
	  <IncludeAllContentForSelfExtract>true</IncludeAllContentForSelfExtract>
	  <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
  <DebugType>none</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="5164023.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.1" />
    <PackageReference Include="QRCoder" Version="1.7.0" />
  </ItemGroup>

</Project>